version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data
    command: >
      redis-server --requirepass ${REDIS_PASSWORD}

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - postgres

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-bot
    volumes:
      - .:/app

networks:
  default:
    driver: bridge

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
